### ISSUE TITLE
请教几个问题

### ISSUE THREAD

**Issue by ycg31** [ClarkeCheng/clash-transparent-proxy-docker#1]
这个透明代理模式必须使用fake-ip模式吗？
另外你的 config.yaml 中缺少 tproxy 设置，   docker-compose.yml 中 image 的名字和你 docker hub 中的名字不一致，导致找不到镜像

**Comment by ClarkeCheng** [comment]
你好，不是必须使用 fake-ip。我自己在使用 redir-host。另外不好意思，config.yaml 和 docker-compose.yml 我之前没注意，但现在已经更新了

**Comment by ycg31** [comment]
还有一个问题很奇怪，  我之前是在openwrt路由器上安装的openclash ，手机使用的qx ，连接家里路由器就改成直连模式，通过路由器上的openclash代理上网。  现在用你的方案把clash安装在服务器docker上面，  不论是fake-ip还是redir-host模式 都会出现手机部分国内直连的网站无法上网，比如jd和tb。应该如何排查问题，clash日志中已经显示走的直连了
[TCP] 192.168.100.114:62062 --> api.m.jd.com match DomainSuffix(jd.com) using ⚪Domestic[DIRECT]

**Comment by ycg31** [comment]
目前 google  youtube  zhihu 国内国外网站都可以访问  就jd和淘宝不正常  奇怪了  连openclash又正常

**Comment by ClarkeCheng** [comment]
> 还有一个问题很奇怪， 我之前是在openwrt路由器上安装的openclash ，手机使用的qx ，连接家里路由器就自动成直连模式，通过路由器上的openclash代理上网。
> 现在用你的方案把clash安装在服务器docker上面， 不论是fake-ip还是redir-host模式 ，如果使用qx，qx设置直连都会出现手机部分国内直连的网站无法上网，比如jd和tb。clash日志中已经显示走的直连了。关闭qx则正常，问题是openclash的话qx开启也正常。
> [TCP] 192.168.100.114:62062 --> api.m.jd.com match DomainSuffix(jd.com) using ⚪Domestic[DIRECT]
> 
> 应该如何排查哈？

你把 clash

**Comment by ycg31** [comment]
> > 还有一个问题很奇怪， 我之前是在openwrt路由器上安装的openclash ，手机使用的qx ，连接家里路由器就自动成直连模式，通过路由器上的openclash代理上网。
> > 现在用你的方案把clash安装在服务器docker上面， 不论是fake-ip还是redir-host模式 ，如果使用qx，qx设置直连都会出现手机部分国内直连的网站无法上网，比如jd和tb。clash日志中已经显示走的直连了。关闭qx则正常，问题是openclash的话qx开启也正常。
> > [TCP] 192.168.100.114:62062 --> api.m.jd.com match DomainSuffix(jd.com) using ⚪Domestic[DIRECT]
> > 应该如何排查哈？
> 
> 你把 clash 装在服务器上了？按道理这个应该装在你家里的软路由上

我软路由本来就是服务器虚拟出来的， 之前是安装在openwrt系统下的openclash  现在我直接虚拟了一个docker安装的clash，头大了，主要是对iptable不熟悉。  我现在连接openclash或者直接连接主路由，手机开qx直连模式都可以正常访问jd。现在问题是：我连接docker clash的话，手机不使用qx的话，都打开jd，使用qx直连就出现jd无法获取dns。

**Comment by ClarkeCheng** [comment]
> > > 还有一个问题很奇怪， 我之前是在openwrt路由器上安装的openclash ，手机使用的qx ，连接家里路由器就自动成直连模式，通过路由器上的openclash代理上网。
> > > 现在用你的方案把clash安装在服务器docker上面， 不论是fake-ip还是redir-host模式 ，如果使用qx，qx设置直连都会出现手机部分国内直连的网站无法上网，比如jd和tb。clash日志中已经显示走的直连了。关闭qx则正常，问题是openclash的话qx开启也正常。
> > > [TCP] 192.168.100.114:62062 --> api.m.jd.com match DomainSuffix(jd.com) using ⚪Domestic[DIRECT]
> > > 应该如何排查哈？
> > 
> > 
> > 你把 clash 装在服务器上了？按道理这个应该装在你家里的软路由上
> 
> 我软路由本来就是服务器虚拟出来的， 之前是安装在openwrt系统下的openclash 现在我直接虚拟了一个docker安装的clash，头大了，主要是对iptable不熟悉。 我现在连接openclash或者直接连接主路由，手机开qx直连模式都可以正常访问jd。现在问题是：我连接docker clash的话，手机不使用qx的话，都打开jd，使用qx直连就出现jd无法获取dns。

我从来不用qx，所以qx的问题我是无法解答的。不过我可以告诉你的是，用了这个镜像后，只要你把你手机的网关和DNS设成容器IP后，就已经能翻墙了（前提是规则和代理要正确），已经没必要在手机上再开一个VPN软件了

**Comment by ycg31** [comment]
> > > > 还有一个问题很奇怪， 我之前是在openwrt路由器上安装的openclash ，手机使用的qx ，连接家里路由器就自动成直连模式，通过路由器上的openclash代理上网。
> > > > 现在用你的方案把clash安装在服务器docker上面， 不论是fake-ip还是redir-host模式 ，如果使用qx，qx设置直连都会出现手机部分国内直连的网站无法上网，比如jd和tb。clash日志中已经显示走的直连了。关闭qx则正常，问题是openclash的话qx开启也正常。
> > > > [TCP] 192.168.100.114:62062 --> api.m.jd.com match DomainSuffix(jd.com) using ⚪Domestic[DIRECT]
> > > > 应该如何排查哈？
> > > 
> > > 
> > > 你把 clash 装在服务器上了？按道理这个应该装在你家里的软路由上
> > 
> > 
> > 我软路由本来就是服务器虚拟出来的， 之前是安装在openwrt系统下的openclash 现在我直接虚拟了一个docker安装的clash，头大了，主要是对iptable不熟悉。 我现在连接openclash或者直接连接主路由，手机开qx直连模式都可以正常访问jd。现在问题是：我连接docker clash的话，手机不使用qx的话，都打开jd，使用qx直连就出现jd无法获取dns。
> 
> 我从来不用qx，所以qx的问题我是无法解答的。不过我可以告诉你的是，用了这个镜像后，只要你把你手机的网关和DNS设成容器IP后，就已经能翻墙了（前提是规则和代理要正确），已经没必要在手机上再开一个VPN软件了

终于解决了！我在docker里直接防火墙添加dns转发就正常了。
    iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53	
    iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53

我手机用qx的目的是离开家的时候qx代理，  在家的时候qx判断ssid 切换成直连 用家里的代理上网
另外tun模式和这个tproxy模式  你觉得哪个更好点，现在clash的tun内核是闭源的  还有其他开源的tun分支吗

**Comment by ClarkeCheng** [comment]
> > > > > 还有一个问题很奇怪， 我之前是在openwrt路由器上安装的openclash ，手机使用的qx ，连接家里路由器就自动成直连模式，通过路由器上的openclash代理上网。
> > > > > 现在用你的方案把clash安装在服务器docker上面， 不论是fake-ip还是redir-host模式 ，如果使用qx，qx设置直连都会出现手机部分国内直连的网站无法上网，比如jd和tb。clash日志中已经显示走的直连了。关闭qx则正常，问题是openclash的话qx开启也正常。
> > > > > [TCP] 192.168.100.114:62062 --> api.m.jd.com match DomainSuffix(jd.com) using ⚪Domestic[DIRECT]
> > > > > 应该如何排查哈？
> > > > 
> > > > 
> > > > 你把 clash 装在服务器上了？按道理这个应该装在你家里的软路由上
> > > 
> > > 
> > > 我软路由本来就是服务器虚拟出来的， 之前是安装在openwrt系统下的openclash 现在我直接虚拟了一个docker安装的clash，头大了，主要是对iptable不熟悉。 我现在连接openclash或者直接连接主路由，手机开qx直连模式都可以正常访问jd。现在问题是：我连接docker clash的话，手机不使用qx的话，都打开jd，使用qx直连就出现jd无法获取dns。
> > 
> > 
> > 我从来不用qx，所以qx的问题我是无法解答的。不过我可以告诉你的是，用了这个镜像后，只要你把你手机的网关和DNS设成容器IP后，就已经能翻墙了（前提是规则和代理要正确），已经没必要在手机上再开一个VPN软件了
> 
> 终于解决了！我在docker里直接防火墙添加dns转发就正常了。
> iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
> iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53
> 
> 我手机用qx的目的是离开家的时候qx代理， 在家的时候qx判断ssid 切换成直连 用家里的代理上网
> 另外tun模式和这个tproxy模式 你觉得哪个更好点，现在clash的tun内核是闭源的 还有其他开源的tun分支吗

我还没折腾成功过 tun，索性就不用 tun 了，我觉得 tproxy 模式挺好用的，就是有一个缺点，不能代理 docker 容器的宿主机的流量。我不用 tun，所以也不知道有没有开源的带 tun 的 clash

**Comment by ycg31** [comment]
> > > > > > 还有一个问题很奇怪， 我之前是在openwrt路由器上安装的openclash ，手机使用的qx ，连接家里路由器就自动成直连模式，通过路由器上的openclash代理上网。
> > > > > > 现在用你的方案把clash安装在服务器docker上面， 不论是fake-ip还是redir-host模式 ，如果使用qx，qx设置直连都会出现手机部分国内直连的网站无法上网，比如jd和tb。clash日志中已经显示走的直连了。关闭qx则正常，问题是openclash的话qx开启也正常。
> > > > > > [TCP] 192.168.100.114:62062 --> api.m.jd.com match DomainSuffix(jd.com) using ⚪Domestic[DIRECT]
> > > > > > 应该如何排查哈？
> > > > > 
> > > > > 
> > > > > 你把 clash 装在服务器上了？按道理这个应该装在你家里的软路由上
> > > > 
> > > > 
> > > > 我软路由本来就是服务器虚拟出来的， 之前是安装在openwrt系统下的openclash 现在我直接虚拟了一个docker安装的clash，头大了，主要是对iptable不熟悉。 我现在连接openclash或者直接连接主路由，手机开qx直连模式都可以正常访问jd。现在问题是：我连接docker clash的话，手机不使用qx的话，都打开jd，使用qx直连就出现jd无法获取dns。
> > > 
> > > 
> > > 我从来不用qx，所以qx的问题我是无法解答的。不过我可以告诉你的是，用了这个镜像后，只要你把你手机的网关和DNS设成容器IP后，就已经能翻墙了（前提是规则和代理要正确），已经没必要在手机上再开一个VPN软件了
> > 
> > 
> > 终于解决了！我在docker里直接防火墙添加dns转发就正常了。
> > iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
> > iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53
> > 我手机用qx的目的是离开家的时候qx代理， 在家的时候qx判断ssid 切换成直连 用家里的代理上网
> > 另外tun模式和这个tproxy模式 你觉得哪个更好点，现在clash的tun内核是闭源的 还有其他开源的tun分支吗
> 
> 我还没折腾成功过 tun，索性就不用 tun 了，我觉得 tproxy 模式挺好用的，就是有一个缺点，不能代理 docker 容器的宿主机的流量。我不用 tun，所以也不知道有没有开源的带 tun 的 clash

https://github.com/Dreamacro/clash/pull/1117
你研究下这个 说是可以代理本机流量
