### ISSUE TITLE
带宽测速跑不到500M。

### ISSUE THREAD

**Issue by piaoyizy** [ClarkeCheng/clash-transparent-proxy-docker#2]
用了这个容器docker跑不满500M（speedtet）,

用了 openwrt的容器 +openclash，可以跑满带宽。

请帮忙看看什么原因。

redir-port: 7892
port: 7890
tproxy-port: 7893
socks-port: 10800
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
dns:
  enable: true
  ipv6: false
  listen: :53
  enhanced-mode: redir-host
  default-nameserver:
    - 8.8.8.8
    - 8.8.4.4
  nameserver:
    - 8.8.8.8
    - 8.8.4.4
  fallback:
    - tls://dns.rubyfish.cn:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
proxies:

**Comment by ClarkeCheng** [comment]
请问你用什么硬件？配置如何？

**Comment by piaoyizy** [comment]
N1盒子，刷的armbian ，  

发现，如果 docker+openwrt的openclash插件，可以跑满。

**Comment by ClarkeCheng** [comment]
这不是bug，建议换性能更好的设备

**Comment by piaoyizy** [comment]
> 这不是bug，建议换性能更好的设备

https://lancellc.gitbook.io/clash/start-clash/clash-udp-tproxy-support 搞定了
