### ISSUE TITLE
关于clash支持带宽测速度的特性

### ISSUE THREAD

**Issue by Pointvar** [ClarkeCheng/clash-transparent-proxy-docker#5]
你好，看到你在clash仓库下提交的issue。我觉得你提的很好，现在我只能在stairspeedtest下完成测试。自己手工更新配置文件。感觉这个有点麻烦的，请问你有其他比较好的实践吗

**Comment by ClarkeCheng** [comment]
你好，issue 是用来给程序提交 bug 或建议的，与这两者无关的内容请不要发 issue，可以发在 discussions。你说的这个问题，除了自己开发，没有什么解决方法
